### ISSUE TITLE
[new] plugin.video.audrey

### ISSUE THREAD

**Issue by ptom98** [xbmc/repo-plugins#1656]
### Add-on details:
- **General**
  - Add-on name: Audrey
  - Add-on ID: plugin.video.audrey
  - Version number: 1.0.0
  - Kodi/repository version: Krypton
- **Code location**
  - URL: https://github.com/ptom98/PTOM/tree/master/plugin.video.audrey
  - Revision/tag: a0f9cb7
  - Branch: master

### Description of changes:
Using Audrey you can use a simple JSON file to scrape video content from websites. You can view the content in Kodi by either viewing within the Audrey addon itself or by creating a whole new addon.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by Lunatixz** [comment]
There are a few issues with this submission. 

1. You need to correct the malformed addon.xml you are missing required elements like api version. https://kodi.wiki/view/Addon.xml

2. Your preconfigured json list includes a number of questionable video sources.
(ie. just because a video is hosted on a popular website, doesn't make it legal to distribute.)

3. Please review repository guidelines you are required to include license information and include that information in your code. https://kodi.wiki/view/Add-on_rules

4. Can you create new plugin art that represents the correct name? The art maybe confusing since it features a name that differences from the plugins id.

Thanks
