### ISSUE TITLE
service.yeemee v5.0.0

### ISSUE THREAD

**Issue by DaLanik** [xbmc/repo-plugins#2943]
### Add-on details:

- **General**
  - Add-on name: YeeMee
  - Add-on ID: service.yeemee
  - Version number: 5.00
  - Kodi/repository version: 19.x

- **Code location**
  - URL: http://kodi.lanik.org/_p3repo/service.yeemee/service.yeemee-5.00.zip
  - Revision/tag: 1.0.0
  - Branch: master

### Description of changes:

https://forum.kodi.tv/showthread.php?tid=313197

This addon controls Xiaomi Yeelight from Kodi and has ambilight functionality.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by enen92** [comment]
Can you submit a pull request instead?

**Comment by DaLanik** [comment]
Sure, I was following instructions in wiki :) Will, submit.

**Comment by enen92** [comment]
Can you point to it? We are really short on people to also have to handle prs :)

**Comment by DaLanik** [comment]
Sorry I'm having a hard time understanding what to do as I never used GitHub :) Point to what?

**Comment by enen92** [comment]
To the wiki article that says repo submissions should be done as issues and not pull requests :)

**Comment by DaLanik** [comment]
I'm trying to submit addon, not repo, but thought link to repo where it is should be enough :) Can I point directly to the addon .zip file?

**Comment by DaLanik** [comment]
OK, so i changed the link to point directly to the addon zip.

**Comment by enen92** [comment]
sorry @DaLanik I think some miscommunication is going on.

I asked if you could submit the addon as a pull request to this project (either Leia ou Matrix branch depending on your goal) instead of opening this issue asking for someone (probably me) to handle it for you.

Since you said you could do the PR (and the reason for opening an issue was just you following instructions on some wiki page), I asked if you could also send me the link to the wiki page that you were following - so that we can discuss it internally (I am not familiar with that page). At the moment we don't have too many people handling the repo, so having to manage submissions as issues + review all submissions via pull requests is simply too much. So, please go ahead and submit your addon as a pull request.

**Comment by DaLanik** [comment]
Sure, here is the link to the wiki. Sorry, I'm doing my best :)

https://kodi.wiki/view/Submitting_Add-ons#Issue_ticket

It says, if I understand correctly:

3.2 Issue ticket

If you are not experienced yet with git and pull requests you may also use the "issue" option where you submit a request to get you add-on added. In this ticket you need to provide the basic information needed so our repo maintainers know where to get the correct version.

**Comment by enen92** [comment]
Thanks, I'll bring the discussion internally to see if the option can be dropped. It's really preferable if you can just submit a pull request (Leia or Matrix) to this project instead of an issue. We are also working on ways to automate the submissions:

https://github.com/xbmc/action-kodi-addon-submitter

It lacks a bit of documentation yet (step by step guides) but it is already used by some addons. See for instance: https://github.com/enen92/script.tubecast/blob/master/.github/workflows/addon-submitter.yml

**Comment by DaLanik** [comment]
I'll have a look... what about my addon submission? :)

**Comment by enen92** [comment]
Send a pull request? :)

**Comment by DaLanik** [comment]
OMG, this is ridiculous....

**Comment by abhishekfdd** [comment]
Still can't see Yeemee on KODI repo, any updates ?

**Comment by enen92** [comment]
No updates, add-ons have to be sent via pull requests either by the author (or any new maintainers once the author stops supporting the add-on). We no longer accept add-on submissions via issues (except skins).
